name: Build Example

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
    
env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
      
  example:
    name: Run examples
    runs-on: macOS-13
    strategy:
        matrix:
          iosDestination: ['platform=iOS Simulator,OS=16.0,name=iPhone 14']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set secret
        run: git config --global url."https://${{ secrets.ACTIONS_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      
      - name: Set pipefail
        run: set -euo pipefail

      - name: Set SwiftPM Plugin config
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

      - name: Build iOS
        run: |
          xcodebuild clean build -project "AppExample/Example.xcodeproj" -scheme "Example" | xcpretty && exit ${PIPESTATUS[0]}
        env:
          destination: ${{ matrix.iosDestination }}
