name: Build Example

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
  
env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:

  swiftpm:
    name: Build SwiftPM
    runs-on: macOS-13
    strategy:
        matrix:
          packages: [OversizeKit, OversizeAdsKit, OversizeCalendarKit, OversizeContactsKit, OversizeLocationKit, OversizeNoticeKit, OversizeNotificationKit, OversizeOnboardingKit, OversizePhotoKit]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set secret
        run: git config --global url."https://${{ secrets.ACTIONS_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      
      - name: Set pipefail
        run: set -euo pipefail

      - name: Set SwiftPM Plugin config
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
        
      - name: Build Package
        run: xcodebuild clean build -skipPackagePluginValidation -scheme ${{ matrix.packages }} -destination 'platform=iOS Simulator,name=iPhone 8,OS=16.4' | xcpretty && exit ${PIPESTATUS[0]}
