name: CI

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build-swiftpm:
    name: Build SwiftPM
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm.yml@main
    strategy:
      matrix:
        packages:
          - OversizeKit
          - OversizeCalendarKit
          - OversizeContactsKit
          - OversizeLocationKit
          - OversizeNoticeKit
          - OversizeNotificationKit
          - OversizeOnboardingKit
          - OversizePhotoKit
        destination:
          - platform=iOS Simulator,name=iPhone 16,OS=18.0
          - platform=macOS,arch=arm64
    with:
      package: ${{ matrix.packages }}
      destination: ${{ matrix.destination }}
    secrets: inherit
    
  build-example:
    name: Build Example
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-app.yml@main
    strategy:
      matrix:
        destination:
          - platform=iOS Simulator,name=iPhone 16,OS=18.0
          - platform=macOS,arch=arm64
    with:
      path: AppExample/Example
      scheme: Example
      destination: ${{ matrix.destination }}
    secrets: inherit

#  tests:
#    name: Test
#    needs: build-swiftpm
#    uses: oversizedev/GithubWorkflows/.github/workflows/test.yml@main
#    secrets: inherit

  bump:
    name: Bump version
    needs: build-example
    if: github.ref == 'refs/heads/main'
    uses: oversizedev/GithubWorkflows/.github/workflows/bump.yml@main
    secrets: inherit
