name: CI - Pull Request
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build-swiftpm:
    name: Build SwiftPM
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm.yml@main
    strategy:
      matrix:
        packages: [OversizeKit, OversizeCalendarKit, OversizeContactsKit, OversizeLocationKit, OversizeNoticeKit, OversizeNotificationKit, OversizeOnboardingKit, OversizePhotoKit]
    with:
      package: ${{ matrix.packages }}
    secrets: inherit
    
  build-example:
    name: Build Example
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-app.yml@main
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2', 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (6th generation),OS=17.2']
    with:
      path: AppExample/Example
      scheme: Example
      destination: ${{ matrix.destination }}
    secrets: inherit
    
#  tests:
#    name: Test
#    needs: build-example
#    uses: oversizedev/GithubWorkflows/.github/workflows/test.yml@main
#    secrets: inherit
