name: CI - Pull Request
on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
jobs:

  build-swiftpm:
    name: Build SwiftPM
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm.yml@main
    strategy:
      matrix:
        packages: [OversizeKit, OversizeAdsKit, OversizeCalendarKit, OversizeContactsKit, OversizeLocationKit, OversizeNoticeKit, OversizeNotificationKit, OversizeOnboardingKit, OversizePhotoKit]
    with:
      package: ${{ matrix.packages }}
    secrets: inherit
    
  build-example:
    name: Build Example
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-ios-app.yml@main
    with:
      folder: AppExample
      app: Example
    secrets: inherit
    
#  tests:
#    name: Test
#    needs: build-example
#    uses: oversizedev/GithubWorkflows/.github/workflows/test.yml@main
#    secrets: inherit
