name: CI - Push

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:

  build-example:
    name: Build Example
    uses: oversizedev/GithubWorkflows/.github/workflows/build-ios-app.yml@main
    with:
      folder: AppExample
      app: Example
    secrets: inherit

  build-swiftpm:
    name: Build SwiftPM
    needs: build-example
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm.yml@main
    strategy:
      matrix:
        packages: [OversizeKit]
    with:
      package: ${{ matrix.packages }}
    secrets: inherit
    
  tests:
    name: Test
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/test.yml@main
    secrets: inherit
    
  bump:
    name: Bump version
    needs: tests
    uses: oversizedev/GithubWorkflows/.github/workflows/bump.yml@main
    secrets: inherit
    
